<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HarfBuzzSharp" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.macOS" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Win32" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" />
  </ItemGroup>

</Project>
